# Replace the text below to customize your site
site_name: Antonio de Jesus Anaya Hernandez - Fab Academy
site_description: Fab Academy documentation site for Antonio de Jesus Anaya Hernandez
site_author: Antonio de Jesus Anaya Hernandez
copyright: Copyright 2021 Antonio de Jesus Anaya Hernandez - Creative Commons Attribution Non Commercial

site_url: http://fabacademy.org/2021/labs/agrilab/students/antonio-anaya

extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/le_anayeau/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/antonio.anayahernande
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AnayaAntonio4
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/antonio-anaya-62586a1a8/

theme:
  name: material
  palette:
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: deep
    accent: indigo
  font:
    # See available fonts at https://fonts.google.com/
    text: Ubuntu
    code: Ubuntu Mono
  icon:
    logo: material/school
  favicon: images/favicon.svg
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
